name: Continuous Integration
on:
  pull_request:
jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: yarn install

      - name: Run Checks
        run: yarn check-all

      - name: Run Build
        run: yarn build

      - name: Run Tests
        run: yarn test:unit:ci
